#!/bin/bash

if [ ${FACILITY:=${PSI_GFA_FACILITY:=SF}} == SF ]; then FACILITY=SWISSFEL; fi

for i in $(
    wget -q -O - "http://epics-boot-info.psi.ch/find-channel.aspx/%:TOD?limit=0&format=csv&header=no&facility=$FACILITY" | sort -V \
    | awk -F : '{print $1}')
do
    BL=$(caget  -noname -nostat $i:CALINK_BROKEN) >/dev/null 2>&1 && [ $BL -gt 0 ] && echo $i $BL
done
